[package]
name = "f4y-example"
version = "0.1.0"
edition = "2024"

[dependencies]
topcoat = { version = "0.9.0", features = [
    "font-fontsource",
    "tailwind",
    "ui",
] }
tokio = { version = "1.53.1", features = ["rt-multi-thread", "macros"] }

[build-dependencies]
topcoat = { version = "0.9.0", default-features = false, features = [
    "tailwind",
] }
