[package]
name = "f4y-example"
version = "0.1.0"
edition = "2024"

[dependencies]
topcoat = { version = "0.9.0", features = [
    "font-fontsource",
    "icon-iconify",
    "tailwind",
    "ui",
] }
tokio = { version = "1.53.1", features = ["rt-multi-thread", "macros"] }
toasty = { version = "0.11.0", features = ["sqlite", "jiff", "migration"] }
jiff = "0.2.37"
serde = { version = "1.0.229", features = ["derive"] }

[build-dependencies]
topcoat = { version = "0.9.0", default-features = false, features = [
    "icon-iconify",
    "tailwind",
] }
